### ISSUE TITLE
error invalid URL escape "%4S"

### ISSUE THREAD

**Issue by weaming** [loveczp/fqimg#3]
After executing `curl --data-binary @test.jpg "http://localhost:12345/put"` show error:

```
{"error":"invalid URL escape \"%4S\""}%
```

**Comment by loveczp** [comment]
curl -F "file=@xxxxx.jpg" "http://fanqiangti.net/put"
现在可以直接测试下上面的命令。
其实就是模拟页面的上的form表单的提交

过年期间对fqimg做了重大的重构，去掉了一个binnary的上传模式。
现在只支持multipart/form-data的上传模式。

非常感谢你的反馈。
